"""
Microsoft Agent Framework (MAF) Hosted Agent Wrapper.

This wrapper handles deployment of agents as hosted agents using the
Microsoft Agent Framework on Azure AI Foundry. Hosted agents are
containerized and run custom code.

Used for: Stay agent

Design doc reference (lines 1527-1646):
    - ImageBasedHostedAgentDefinition
    - azure-ai-agentserver-agentframework package
    - Container protocol with AgentServer.handler decorator
"""

from pathlib import Path
from typing import Any

from .base_wrapper import AgentConfig, BaseAgentWrapper


class MAFHostedWrapper(BaseAgentWrapper):
    """Wrapper for deploying agents as MAF hosted agents.

    Hosted agents using Microsoft Agent Framework are containerized
    and deployed to Foundry's managed runtime. They can execute
    arbitrary Python code while conforming to the hosted agent protocol.

    The wrapper generates:
    - main.py with AgentServer.handler pattern
    - Dockerfile for containerization
    - requirements.txt with azure-ai-agentserver-agentframework
    - agent.yaml for Foundry deployment
    """

    DEFAULT_REQUIREMENTS = [
        "azure-ai-agentserver-agentframework",
        "pydantic>=2.0",
    ]

    def wrap(self) -> None:
        """Prepare the hosted agent wrapper.

        For hosted agents, we don't extract instructions from source code.
        Instead, we prepare the wrapper to generate deployment artifacts
        that will import and use the existing agent logic.

        Raises:
            FileNotFoundError: If source agent code is not found.
        """
        agent_module = self._find_agent_module()
        if not agent_module:
            raise FileNotFoundError(
                f"Could not find agent module in {self.source_path}"
            )

        # Store the module path for later use in generating main.py
        self._agent_module_path = agent_module
        self._wrapped = True

    def _find_agent_module(self) -> Path | None:
        """Find the agent module directory.

        Returns:
            Path to the agent module if found, None otherwise.
        """
        # Check if source_path is absolute or relative
        if self.source_path.is_absolute():
            base_path = self.source_path
        else:
            base_path = Path.cwd() / self.source_path

        # Check if it's a valid Python module (has __init__.py or agent.py)
        if base_path.exists():
            if (base_path / "agent.py").exists() or (base_path / "__init__.py").exists():
                return base_path

        return None

    def get_config(self) -> dict[str, Any]:
        """Get the hosted agent configuration.

        Returns:
            Dictionary containing:
            - agent_yaml: Configuration for agent.yaml
            - main_py: Content for main.py
            - dockerfile: Content for Dockerfile
            - requirements_txt: Content for requirements.txt

        Raises:
            RuntimeError: If wrap() has not been called.
        """
        self._ensure_wrapped()

        return {
            "agent_yaml": self._generate_agent_yaml(),
            "main_py": self._generate_main_py(),
            "dockerfile": self._generate_dockerfile(),
            "requirements_txt": self._generate_requirements(),
        }

    def _generate_agent_yaml(self) -> dict[str, Any]:
        """Generate agent.yaml configuration."""
        config: dict[str, Any] = {
            "name": self.name,
            "type": "hosted",
            "framework": "agent_framework",
            "description": f"Hosted agent wrapping {self._config.source_path}",
        }

        if self._config.env_vars:
            config["env_vars"] = self._config.env_vars

        return config

    def _generate_main_py(self) -> str:
        """Generate main.py content for the hosted agent."""
        # Convert source path to import path
        import_path = str(self._config.source_path).replace("/", ".").replace("\\", ".")
        if import_path.startswith("src."):
            import_path = import_path[4:]  # Remove 'src.' prefix for cleaner imports

        return f'''"""
Hosted Agent: {self.name}

This file wraps the existing agent logic from {self._config.source_path}
for deployment as a hosted agent on Azure AI Foundry.

Generated by interoperability/shared/agent_wrappers/maf_hosted_wrapper.py
"""

import logging
from typing import Any

from azure.ai.agentserver import AgentServer

# Import the existing agent logic
# Note: The source path is added to PYTHONPATH in the container
from {import_path}.agent import *  # noqa: F401, F403

logger = logging.getLogger(__name__)

# Create the agent server instance
server = AgentServer()


@server.handler
async def handle_message(message: dict[str, Any]) -> dict[str, Any]:
    """Handle incoming messages using the wrapped agent logic.

    Args:
        message: The incoming message from Foundry.

    Returns:
        The agent's response.
    """
    # TODO: Implement actual message handling using the imported agent
    # This requires understanding the specific agent's interface
    logger.info("Received message: %s", message)

    return {{
        "response": "Hosted agent processing not yet implemented",
        "agent": "{self.name}",
    }}


if __name__ == "__main__":
    server.run()
'''

    def _generate_dockerfile(self) -> str:
        """Generate Dockerfile content."""
        return f'''# Hosted Agent: {self.name}
# Built for Azure AI Foundry hosted agent deployment

FROM python:3.11-slim

WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the agent code
COPY . .

# Add src to Python path for imports
ENV PYTHONPATH=/app/src:$PYTHONPATH

# Expose the default agent server port
EXPOSE 8080

# Run the agent server
CMD ["python", "main.py"]
'''

    def _generate_requirements(self) -> str:
        """Generate requirements.txt content."""
        requirements = self.DEFAULT_REQUIREMENTS.copy()

        # Add any additional requirements from config
        # (could be extended based on source agent analysis)

        return "\n".join(requirements)

    def deploy(self, dry_run: bool = False) -> dict[str, Any]:
        """Deploy the hosted agent to Azure AI Foundry.

        Args:
            dry_run: If True, only print what would be deployed.

        Returns:
            Deployment result dictionary.

        Raises:
            RuntimeError: If wrap() has not been called.
        """
        self._ensure_wrapped()

        config = self.get_config()

        if dry_run:
            return {
                "success": True,
                "agent_id": None,
                "message": (
                    f"[DRY RUN] Would deploy hosted agent (MAF) '{self.name}'\n"
                    f"  - Build container from Dockerfile\n"
                    f"  - Push to ACR\n"
                    f"  - Register with Foundry"
                ),
                "config": config,
            }

        # Actual deployment requires:
        # 1. Build Docker container
        # 2. Push to Azure Container Registry
        # 3. Register hosted agent with Foundry
        return {
            "success": False,
            "agent_id": None,
            "message": "Actual hosted agent deployment not yet implemented.",
            "config": config,
        }
